"""Generate data/fees.yaml from the archived primary artifacts.

fees.yaml is a DERIVED file. Its inputs are both in the repo:

  docs/sources/fees/*.pdf              16 archived captures of Kalshi's own
                                       published fee schedule, 2021-07 .. 2026-02
  docs/sources/fees/version_history.json  parsed from those PDFs by
                                       tools/fetch_fee_schedule_history.py
  data/series_fee_catalog.json         per-series fee_type/fee_multiplier from
                                       Kalshi's API, for the period the PDFs
                                       stopped enumerating scope

Regenerate with:  python tools/build_fees_yaml.py

Editing fees.yaml by hand is a mistake -- it will be overwritten, and worse, a
hand edit is a fee number with no artifact behind it, which is exactly what
spec S7 names as this replication's most error-prone failure mode.

Three structural facts the previous hand-written schedule got wrong, all
visible in the artifacts and all load-bearing:

1. The maker fee is a PER-SERIES SURCHARGE, not a market-wide regime. Every
   dated version enumerates the series it applies to; the general section says
   in terms that resting orders are free "unless they are included in our
   'Maker Fees' section".
2. Its first form was FLAT per contract -- round up(0.0025 x C), with no price
   dependence at all -- and only became the quadratic 0.0175 x C x P x (1-P)
   on 2025-07-08.
3. S&P500 (INX*) and NASDAQ-100 (NASDAQ100*) markets pay HALF the general
   taker rate (0.035), in every version from 2022-09 onward. That carve-out
   covers 18.3% of R1's in-scope universe.

And one that changes R1's earliest window: the taker rate was 0.14 in the
2021-07-20 capture, not 0.07.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HISTORY = ROOT / "docs" / "sources" / "fees" / "version_history.json"
CATALOG = ROOT / "data" / "series_fee_catalog.json"
OUT = ROOT / "data" / "fees.yaml"

# Our own universe's earliest in-scope market close (2021-07-01) predates the
# earliest archived capture (2021-07-20) by three weeks. Rather than raise a
# schedule gap on those rows, the earliest KNOWN rate is carried back to the
# start of our data and the assumption is stated here and in the file header.
DATA_FLOOR = "2021-07-01"
# The 0.07 rate is not written as a formula in the 2021-08-01 capture; it is
# read off that capture's fee TABLE ($1.75 per 100 contracts at $0.50 =>
# 0.07 x 100 x 0.25). The switch from 0.14 is therefore bracketed to
# (2021-07-20, 2021-08-01] and dated at the later end -- the conservative
# choice, since it keeps the higher rate in force for every day it might
# still have applied.
TAKER_007_FROM = "2021-08-01"
INDEX_PREFIXES = ["INX", "NASDAQ100"]


def _load() -> tuple[list[dict], dict]:
    history = json.loads(HISTORY.read_text(encoding="utf-8"))
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    return history, catalog


def _maker_versions(history: list[dict]) -> list[dict]:
    """Dated maker-fee versions, de-duplicated: several captures share one
    effective date (the archive caught the same document twice), and a capture
    with no stamp cannot be placed on the step function at all."""
    seen: dict[str, dict] = {}
    for v in history:
        if not v["effective_from"] or not v["maker_series"]:
            continue
        seen.setdefault(v["effective_from"], v)
    return [seen[k] for k in sorted(seen)]


def _index_carveout_from(history: list[dict]) -> str:
    """First capture showing the S&P/NASDAQ half-rate table. Captures carry no
    self-dated stamp before 2025, so the capture date is the best evidence --
    it bounds the carve-out as already public by then, which is the direction
    that matters (it cannot have started later)."""
    for v in history:
        if v["index_carveout_rates"]:
            ts = v["capture"]
            return f"{ts[0:4]}-{ts[4:6]}-{ts[6:8]}"
    return ""


def _yaml_list(items: list[str], indent: int) -> str:
    pad = " " * indent
    return "\n".join(f"{pad}- {item}" for item in items)


def build() -> str:
    history, catalog = _load()
    maker_versions = _maker_versions(history)
    index_from = _index_carveout_from(history)
    today = sorted(t for t, s in catalog["series"].items() if "maker" in str(s.get("fee_type", "")).lower())
    last_dated = maker_versions[-1]
    lower = sorted(set(last_dated["maker_series"]) & set(today))
    upper = sorted(set(last_dated["maker_series"]) | set(today))
    generated = datetime.now(UTC).strftime("%Y-%m-%d")

    lines: list[str] = []
    add = lines.append
    add(f"# GENERATED by tools/build_fees_yaml.py on {generated} -- do not hand-edit.")
    add("#")
    add("# Kalshi fee history, sourced from primary artifacts (spec S3/S7): a")
    add("# right-continuous step function keyed on trade FILL timestamp, never")
    add("# seeded from a 'current' row backwards.")
    add("#")
    add("# Evidence, all archived in this repo:")
    add(f"#   docs/sources/fees/*.pdf                 {len(history)} dated captures of Kalshi's own")
    add("#                                           published fee schedule, 2021-07 .. 2026-02")
    add("#   docs/sources/fees/version_history.json  machine-parsed from those PDFs")
    add("#   data/series_fee_catalog.json            Kalshi API per-series fee_type,")
    add(f"#                                           frozen {catalog['frozen_at']}")
    add("#")
    add("# Entry shape:")
    add("#   form: quadratic          fee = ceil_to_cent(rate * C * P * (1-P))")
    add("#         flat_per_contract  fee = ceil_to_cent(rate * C)      <- 2025-05/06 maker fee")
    add("#         none               fee = 0")
    add("#   scope.kind: all | ticker_prefix | series")
    add("#         Most specific applicable entry wins: series > ticker_prefix > all,")
    add("#         ties broken by the latest effective_from at or before the fill.")
    add("#")
    add("# Three things the earlier hand-written schedule had wrong, each visible")
    add("# in the artifacts and each load-bearing:")
    add("#   1. The maker fee is a PER-SERIES surcharge, never market-wide. Resting")
    add("#      orders are free \"unless they are included in our 'Maker Fees'")
    add("#      section\" -- the general section's own words.")
    add("#   2. Its first form was FLAT per contract, round up(0.0025 x C), with no")
    add("#      price dependence; the quadratic 0.0175 form began 2025-07-08.")
    add("#   3. S&P500 (INX*) and NASDAQ-100 (NASDAQ100*) markets pay HALF the")
    add("#      general taker rate. That covers 18.3% of R1's in-scope universe.")
    add("# And one more: the taker rate was 0.14 in the 2021-07-20 capture.")
    add("#")
    add("# BDW's own dating -- \"Kalshi began to charge fees on Makers after April")
    add("# 2025\" -- is confirmed in direction and sharpened by the documents: the")
    add("# first maker fee is stamped 'Last Updated: May 13, 2025'.")
    add("#")
    add("# KNOWN GAP, carried explicitly rather than papered over: from the")
    add("# 2025-10-01 version Kalshi removed the series list from the PDF and")
    add("# deferred to kalshi.com/fee-schedule, which is client-rendered and whose")
    add("# Wayback captures are empty app shells. Per-series scope between")
    add(f"# {last_dated['effective_from']} and the API freeze is therefore not directly")
    add("# observable. The two dated endpoints are NOT nested (series both joined")
    add("# and left), so these are evidence bounds, not logical ones:")
    add(f"#   lower {len(lower):3d} series -- in the last dated list AND in the API catalog")
    add(f"#   upper {len(upper):3d} series -- in either")
    add("# The primary schedule below uses the lower set; the fee-sensitivity")
    add("# ribbon (spec S4) reports the span.")
    add("")
    add("version: 2")
    add("scope_bounds_post_pdf:")
    add(f"  effective_from: \"{maker_versions[-1]['effective_from']}\"")
    add("  note: >-")
    add("    Evidence bounds on maker-fee series membership after Kalshi stopped")
    add("    listing it in the PDF. Consumed by the fee-sensitivity ribbon, not by")
    add("    the primary lookup.")
    add("  lower:")
    add(_yaml_list(lower, 4))
    add("  upper:")
    add(_yaml_list(upper, 4))
    add("schedule:")

    # --- taker ---
    add(f"  - effective_from: \"{DATA_FLOOR}\"")
    add("    role: taker")
    add("    form: quadratic")
    add("    rate: 0.14")
    add("    scope: {kind: all}")
    add("    source: kalshi-fee-schedule-20210720193706.pdf")
    add("    note: >-")
    add("      \"fee = roundup(14% x c x p x (1-p))\", with the document's own worked")
    add("      example (1 contract at $0.55 -> $0.04). Carried back three weeks from")
    add("      the capture to our data's earliest in-scope close; no earlier artifact")
    add("      exists.")
    add(f"  - effective_from: \"{TAKER_007_FROM}\"")
    add("    role: taker")
    add("    form: quadratic")
    add("    rate: 0.07")
    add("    scope: {kind: all}")
    add("    source: kalshi-fee-schedule-20210801144246.pdf")
    add("    note: >-")
    add("      Read off that capture's fee table ($1.75 per 100 contracts at $0.50 =")
    add("      0.07 x 100 x 0.25); the formula text was dropped from the document in")
    add("      this vintage and returns, unchanged at 0.07, in the 2022-09-11 capture.")
    add("      The switch from 0.14 is bracketed to (2021-07-20, 2021-08-01] and dated")
    add("      at the later end so the higher rate holds for every day it might still")
    add("      have applied.")
    if index_from:
        add(f"  - effective_from: \"{index_from}\"")
        add("    role: taker")
        add("    form: quadratic")
        add("    rate: 0.035")
        add(f"    scope: {{kind: ticker_prefix, prefixes: {INDEX_PREFIXES}}}")
        add("    source: kalshi-fee-schedule-20220926004130.pdf")
        add("    note: >-")
        add("      Half-rate carve-out for S&P500 and Nasdaq-100 markets, by MARKET")
        add("      ticker prefix (the document's own rule: \"any other market beginning")
        add("      with the INX ticker\"). Present in every later capture through")
        add("      2026-02. BDW apply a single 0.07 to their whole sample, so R1's")
        add("      primary reproduction does too and this entry drives the sensitivity")
        add("      branch -- see docs/r1_reproduction_findings.md.")

    # --- maker ---
    add(f"  - effective_from: \"{DATA_FLOOR}\"")
    add("    role: maker")
    add("    form: none")
    add("    rate: 0.0")
    add("    scope: {kind: all}")
    add("    source: kalshi-fee-schedule-20210720193706.pdf")
    add("    note: >-")
    add("      \"We do not charge a fee to 'liquidity makers'\". Never superseded for")
    add("      series outside a maker-fee list -- which is why a series-scoped entry")
    add("      below leaves every other series correctly at zero.")
    for v in maker_versions:
        rate = (v["maker_rates_quadratic"] or v["maker_rates_flat"])[0]
        form = "quadratic" if v["maker_rates_quadratic"] else "flat_per_contract"
        series = lower if v is last_dated else sorted(v["maker_series"])
        add(f"  - effective_from: \"{v['effective_from']}\"")
        add("    role: maker")
        add(f"    form: {form}")
        add(f"    rate: {rate}")
        add("    scope:")
        add("      kind: series")
        add("      series:")
        add(_yaml_list(series, 8))
        add(f"    source: {v['file']}")
        if v is last_dated:
            add("    note: >-")
            add("      Scope is the LOWER evidence bound (see scope_bounds_post_pdf): the")
            add("      last dated PDF list intersected with the API catalog, because from")
            add("      the 2025-10-01 version onward the document stopped enumerating")
            add("      scope. Rate and form are unchanged from 2025-07-08 in every later")
            add("      capture, so only membership is uncertain here, not the formula.")
    return "\n".join(lines) + "\n"


def main() -> int:
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
